### ISSUE TITLE
Setting Redstone output to 16 by mistake "java.lang.ArrayIndexOutOfBoundsException:"

### ISSUE THREAD

**Issue by Erelaszun** [McJty/RFToolsControl#21]
This was the server crash log:

java.lang.ArrayIndexOutOfBoundsException: 16
	at lumien.randomthings.block.BlockRainbowLamp.func_180650_b(BlockRainbowLamp.java:74)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:743)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

Now... I know the crash happened via Random Things.... but just thinking... to prevent mods from crashing that doesn't have checks for it... maybe put in a safety system for redstone output so it cannot be higher then what is allowed (15).

This happened by mistake as my loop didn't finish when the variable reached 16 as I had hoped.

**Comment by McJty** [comment]
Fixed next release
