### ISSUE TITLE
[ 1.11.2 - v1.6.6 ] Opening Crafting Card results in crash

### ISSUE THREAD

**Issue by GeekBeam** [McJty/RFToolsControl#73]
opening crafting Card results in a crash, due to inability to render the screen.

[[Log](https://puu.sh/uVy2r/d4bf63257e.txt)]

**Comment by McJty** [comment]
I need more information. What item was the crafting card configured for?

**Comment by GeekBeam** [comment]
none at all, was going to load it up for a test, so I isolated a single card from the stack and shift right clicked to open, caused the crash.

**Comment by McJty** [comment]
Ok, will check it out

**Comment by jazzyworld** [comment]
first errorlog when trying to open a crafting card to input a recipe ...
[crash-2017-03-31_15.18.28-client.txt](https://github.com/McJty/RFToolsControl/files/887060/crash-2017-03-31_15.18.28-client.txt)

searched for issues, noticed my rftools mods were out of date so...

everything updated...
[crash-2017-03-31_17.15.15-client.txt](https://github.com/McJty/RFToolsControl/files/887057/crash-2017-03-31_17.15.15-client.txt)

tried it on 2 different creative worlds, same result

**Comment by JustJinxed** [comment]
I'm also having this same exact result. Stripped to barebones just to be sure. 
[crash-2017-04-27_06.57.31-client.txt](https://github.com/McJty/RFToolsControl/files/961798/crash-2017-04-27_06.57.31-client.txt)

forge-1.11.2-13.20.0.2282
compatlayer-1.11.2-0.2.5
mcjtylib-1.1x-2.3.11
rftools-1.1x-6.00
rftoolsctrl-1.1x-1.6.6

**Comment by JustJinxed** [comment]
Saw "Crafting card tooltip fix when the card is empty" in main, Downloaded and compiled latest 1.11 gradle branch, issue has been fixed for a while now (the masters fingers are so... fast!) 👍

**Comment by McJty** [comment]
Really? Um, I thought I was up to date. I'll check it out when I find some time

**Comment by Knito58** [comment]
Crafting card crashes in 1.6.6 with NPE "Rendering screen"
MC 1.11.2 Forge 13.20.0.2285

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777)
	at mcjty.rftoolscontrol.items.craftingcard.GuiCraftingCard$1.getTooltips(GuiCraftingCard.java:83)
	at mcjty.lib.gui.Window.getTooltips(Window.java:155)
	at mcjty.lib.gui.WindowManager.lambda$drawTooltips$5(WindowManager.java:108)
	at mcjty.lib.gui.WindowManager$$Lambda$771/2028807740.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at mcjty.lib.gui.WindowManager.drawTooltips(WindowManager.java:107)
	at mcjty.lib.container.GenericGuiContainer.func_146979_b(GenericGuiContainer.java:84)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:118)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:530)

-- Screen render details --
Details:
	Screen name: mcjty.rftoolscontrol.items.craftingcard.GuiCraftingCard
	Mouse location: Scaled: (320, 234). Absolute: (640, 470)
	Screen size: Scaled: (640, 470). Absolute: (1280, 940). Scale factor of 2

**Comment by McJty** [comment]
This is already fixed but I'll make a new release tomorrow

**Comment by McJty** [comment]
Will release today

**Comment by Knito58** [comment]
Bugfix confirmed! Thank you.
